# Generated by Django 4.2.7 on 2024-01-26 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='Zip',
            new_name='Pin',
        ),
    ]
